sudo: false
language: python
python:
- '2.7'
- '3.4'
before_script:
- pip install pep8
- cat sqlshare_client/VERSION
script:
- pep8 setup.py sqlshare_client/
before_deploy:
- find sqlshare_client/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > sqlshare_client/VERSION
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: CKtl5xtaVjwvIItVVmiFbIrWCER6KIh5PP/n4Gu4qa9oysuqTdOkdMdYe88Iq49LNC/sLr+Fr8ONtfqfpJh9I2BJJqVBaike2ChQhmK0UhTfTpyAjVDdCwocvlC0YVihWWZ6YPZKBJ3nkCVC1/HCmlP3ryWLbHtSm4obkOqWDWVG3uwy0Qk7U/EHzce5qrf+8SRjD4Nwjw4QnKkzec5DXmVfcw0xnR9Ey06IF0ZhtZ1hLctQklubkN5r7Ky++Duz9963ca+sieYJQVIwWPetoev4lukkTs56rfJJEJLmnjsjiiBT52264uwGJN2lICFaGpTKBVmL367TP4UZHgwVpgo+KhlmT6/p1JVPZVpGCRr19kYECdw+H+3E9PIQk6HFa1Q5xT8AqOGVwzQkdv0qMnF1CSJ7axCmfy59IgJ0tnu7s3eQonQuSP4P4BSaImHVCFiGwx/pcDA3H7D6Wzitiy6Wr4TNU3/GFOj5pXJehPciHYIt9X+8UN0i3GS88paf88gIt4mFGOybTLcTaA91jQR9NAQB80CyqY/tfuYpLk1DLULKnmJWh7C0mSLrTUn0yX40Lp3NazAPQlxC0giq0J0EG7+luyxow5KRIloynEWz7Ornu2C+NbBLLEavPIFyK5c+76mHhvQqtnT48h9nCpD+IDU2XvZSwSjkFuZR6q4=
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
