sudo: false
language: python
python:
- '2.7'
- '3.4'
before_script:
- pip install pep8
script:
- pep8 setup.py sqlshare_client/
before_deploy:
- find sqlshare_client/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > sqlshare_client/VERSION
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: Qh6L27BSJo9l6o4bNgwNkiNch0uIFR+nc0/l4S51FZ3nCNlUdfHCw0Qrj+a4y4hmBH8oEROyugSluutX5wSbvTXoUkNQcgi/KY34mVScVv4cucm5OeEo1QiXP1gZJdklEWv4HkDpHW9RTd+r6IQqrawnodO28n4/LTQJCZXNJKn80Rea2ca0b6f3Oe0D2MDjYC0DGCNElEYh/ktTMlR0Ut7szlghZZvNnQSK2BzB1XIezyqSdFp6m1dl/TxbR7yNDmz+Xql+T0T4XPibr0ivc72VIqkPhU8VAAEB5MivIfv2V0/GXYkPEXdViOqN/zcxVjkF1GiueCvruSkSy5zlf7td4bmkWXVmgF9JlcR+xVA2xm9FREdN9dblqZN2igOkvP37n3iB79dQIPL/VF95pKKVcjoYXlTLSBcDbUXXWNwW84peQnZMQaZSAN7DMKnG0jw1sUDL2zdrbLiEC1+wVLAXXTcQmslwruuIMPjEY6yCr3GK6MGVx8Q+HjYN50a++MBAUIyGhqSsqvR6RlkS6kiyMd6eSUHnetW2o/uZ7TBN+1KX80SadBXcEhAcVuf1xxg/2AWkOmFu6KdOd+kX2yvXbtD21xN0zv7+uwo6j26R9yLjPaBjsUiMQ+dI+FDCDBlabXhDatvh9iEPdWCKr4vE8jlqyEY/DO0KZahWsY4=
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
