#!/usr/bin/env python

from sqlshare_client.util.scripts import get_client, dump_dataset
import argparse
import sys

parser = argparse.ArgumentParser()
parser.add_argument('--name', required=True)
parser.add_argument('--is-public', required=False)
parser.add_argument('--description', required=False)
parser.add_argument('--file', required=True)

try:
    client = get_client(parser)
    values = vars(parser.parse_args())
    owner = client.get_current_user()
    dataset = client.create_dataset_from_file(owner.username,
                                              values['name'],
                                              values['file'],
                                              values['description'],
                                              values['is_public'],
                                              visualize=True)
    dump_dataset(dataset)
except IOError as io:
    print "Unable to open file %s: %s" % (values['file'], io[1])
except Exception as ex:
    print "EX: ", ex
    pass

