#!/usr/bin/env python

from sqlshare_client.util.scripts import get_client

try:
    user = get_client().get_current_user()
    print user.username
except Exception as ex:
    print "E: ", ex
    pass

